package cn.cgy.dao;

import cn.cgy.pojo.AwUser;
import java.util.List;

public interface AwUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user
     *
     * @mbggenerated Tue Nov 21 16:06:07 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user
     *
     * @mbggenerated Tue Nov 21 16:06:07 GMT+08:00 2017
     */
    int insertUser(AwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user
     *
     * @mbggenerated Tue Nov 21 16:06:07 GMT+08:00 2017
     */
    AwUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user
     *
     * @mbggenerated Tue Nov 21 16:06:07 GMT+08:00 2017
     */
    List<AwUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aw_user
     *
     * @mbggenerated Tue Nov 21 16:06:07 GMT+08:00 2017
     */
    int updateByPrimaryKey(AwUser record);

    List<AwUser> getUser(AwUser awUser);
}