package cn.cgy.dao;

import cn.cgy.pojo.Classification;
import cn.cgy.pojo.ClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int countByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int deleteByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int insert(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int insertSelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    List<Classification> selectByExample(ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    Classification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByExample(@Param("record") Classification record, @Param("example") ClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(Classification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByPrimaryKey(Classification record);
}