package cn.cgy.dao;

import cn.cgy.pojo.Outpay;
import cn.cgy.pojo.OutpayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int countByExample(OutpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int deleteByExample(OutpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int insert(Outpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int insertSelective(Outpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    List<Outpay> selectByExample(OutpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    Outpay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") Outpay record, @Param("example") OutpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByExample(@Param("record") Outpay record, @Param("example") OutpayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(Outpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outpay
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    int updateByPrimaryKey(Outpay record);
}