package cn.cgy.pojo;

/**
 * 
 * @author CGy 2016-5-4 22:52:44
 */
public class Classification {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification.id
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification.class1
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String class1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification.class2
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String class2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classification.class3
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String class3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification.id
	 * @return  the value of classification.id
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification.id
	 * @param id  the value for classification.id
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification.class1
	 * @return  the value of classification.class1
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getClass1() {
		return class1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification.class1
	 * @param class1  the value for classification.class1
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setClass1(String class1) {
		this.class1 = class1 == null ? null : class1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification.class2
	 * @return  the value of classification.class2
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getClass2() {
		return class2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification.class2
	 * @param class2  the value for classification.class2
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setClass2(String class2) {
		this.class2 = class2 == null ? null : class2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classification.class3
	 * @return  the value of classification.class3
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getClass3() {
		return class3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classification.class3
	 * @param class3  the value for classification.class3
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setClass3(String class3) {
		this.class3 = class3 == null ? null : class3.trim();
	}

	public Classification(int id, String class1, String class2, String class3) {
		super();
		this.id = id;
		this.class1 = class1;
		this.class2 = class2;
		this.class3 = class3;
	}

	public Classification() {
		super();
	}

	@Override
	public String toString() {
		return "Classification [id=" + id + ", class1=" + class1 + ", class2="
				+ class2 + ", class3=" + class3 + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((class1 == null) ? 0 : class1.hashCode());
		result = prime * result + ((class2 == null) ? 0 : class2.hashCode());
		result = prime * result + ((class3 == null) ? 0 : class3.hashCode());
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Classification other = (Classification) obj;
		if (class1 == null) {
			if (other.class1 != null)
				return false;
		} else if (!class1.equals(other.class1))
			return false;
		if (class2 == null) {
			if (other.class2 != null)
				return false;
		} else if (!class2.equals(other.class2))
			return false;
		if (class3 == null) {
			if (other.class3 != null)
				return false;
		} else if (!class3.equals(other.class3))
			return false;
		if (id != other.id)
			return false;
		return true;
	}

}
