package cn.cgy.pojo;

import java.util.ArrayList;
import java.util.List;

public class ClassificationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public ClassificationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClass1IsNull() {
            addCriterion("class1 is null");
            return (Criteria) this;
        }

        public Criteria andClass1IsNotNull() {
            addCriterion("class1 is not null");
            return (Criteria) this;
        }

        public Criteria andClass1EqualTo(String value) {
            addCriterion("class1 =", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1NotEqualTo(String value) {
            addCriterion("class1 <>", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1GreaterThan(String value) {
            addCriterion("class1 >", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1GreaterThanOrEqualTo(String value) {
            addCriterion("class1 >=", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1LessThan(String value) {
            addCriterion("class1 <", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1LessThanOrEqualTo(String value) {
            addCriterion("class1 <=", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1Like(String value) {
            addCriterion("class1 like", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1NotLike(String value) {
            addCriterion("class1 not like", value, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1In(List<String> values) {
            addCriterion("class1 in", values, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1NotIn(List<String> values) {
            addCriterion("class1 not in", values, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1Between(String value1, String value2) {
            addCriterion("class1 between", value1, value2, "class1");
            return (Criteria) this;
        }

        public Criteria andClass1NotBetween(String value1, String value2) {
            addCriterion("class1 not between", value1, value2, "class1");
            return (Criteria) this;
        }

        public Criteria andClass2IsNull() {
            addCriterion("class2 is null");
            return (Criteria) this;
        }

        public Criteria andClass2IsNotNull() {
            addCriterion("class2 is not null");
            return (Criteria) this;
        }

        public Criteria andClass2EqualTo(String value) {
            addCriterion("class2 =", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2NotEqualTo(String value) {
            addCriterion("class2 <>", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2GreaterThan(String value) {
            addCriterion("class2 >", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2GreaterThanOrEqualTo(String value) {
            addCriterion("class2 >=", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2LessThan(String value) {
            addCriterion("class2 <", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2LessThanOrEqualTo(String value) {
            addCriterion("class2 <=", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2Like(String value) {
            addCriterion("class2 like", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2NotLike(String value) {
            addCriterion("class2 not like", value, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2In(List<String> values) {
            addCriterion("class2 in", values, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2NotIn(List<String> values) {
            addCriterion("class2 not in", values, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2Between(String value1, String value2) {
            addCriterion("class2 between", value1, value2, "class2");
            return (Criteria) this;
        }

        public Criteria andClass2NotBetween(String value1, String value2) {
            addCriterion("class2 not between", value1, value2, "class2");
            return (Criteria) this;
        }

        public Criteria andClass3IsNull() {
            addCriterion("class3 is null");
            return (Criteria) this;
        }

        public Criteria andClass3IsNotNull() {
            addCriterion("class3 is not null");
            return (Criteria) this;
        }

        public Criteria andClass3EqualTo(String value) {
            addCriterion("class3 =", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3NotEqualTo(String value) {
            addCriterion("class3 <>", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3GreaterThan(String value) {
            addCriterion("class3 >", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3GreaterThanOrEqualTo(String value) {
            addCriterion("class3 >=", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3LessThan(String value) {
            addCriterion("class3 <", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3LessThanOrEqualTo(String value) {
            addCriterion("class3 <=", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3Like(String value) {
            addCriterion("class3 like", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3NotLike(String value) {
            addCriterion("class3 not like", value, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3In(List<String> values) {
            addCriterion("class3 in", values, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3NotIn(List<String> values) {
            addCriterion("class3 not in", values, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3Between(String value1, String value2) {
            addCriterion("class3 between", value1, value2, "class3");
            return (Criteria) this;
        }

        public Criteria andClass3NotBetween(String value1, String value2) {
            addCriterion("class3 not between", value1, value2, "class3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification
     *
     * @mbggenerated do_not_delete_during_merge Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classification
     *
     * @mbggenerated Sat Jul 16 16:30:21 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}