package cn.cgy.pojo;

import java.math.BigDecimal;

/**
 * 
 * @author CGy
 *
 */
public class Outpay {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outpay.id
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outpay.class_type
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String classType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outpay.type
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outpay.money
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private BigDecimal money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outpay.create_user
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column outpay.create_time
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	private String createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outpay.id
	 * @return  the value of outpay.id
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outpay.id
	 * @param id  the value for outpay.id
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outpay.class_type
	 * @return  the value of outpay.class_type
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getClassType() {
		return classType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outpay.class_type
	 * @param classType  the value for outpay.class_type
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setClassType(String classType) {
		this.classType = classType == null ? null : classType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outpay.type
	 * @return  the value of outpay.type
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outpay.type
	 * @param type  the value for outpay.type
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outpay.money
	 * @return  the value of outpay.money
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public BigDecimal getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outpay.money
	 * @param money  the value for outpay.money
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outpay.create_user
	 * @return  the value of outpay.create_user
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outpay.create_user
	 * @param createUser  the value for outpay.create_user
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column outpay.create_time
	 * @return  the value of outpay.create_time
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column outpay.create_time
	 * @param createTime  the value for outpay.create_time
	 * @mbggenerated  Sat Jul 16 16:30:21 GMT+08:00 2016
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}

	public Outpay() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Outpay(int id, String classType, String type, BigDecimal money,
			String createUser, String createTime) {
		super();
		this.id = id;
		this.classType = classType;
		this.type = type;
		this.money = money;
		this.createUser = createUser;
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "Outpay [id=" + id + ", classType=" + classType + ", type=" + type
				+ ", money=" + money + ", createUser=" + createUser
				+ ", createTime=" + createTime + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((classType == null) ? 0 : classType.hashCode());
		result = prime * result
				+ ((createTime == null) ? 0 : createTime.hashCode());
		result = prime * result
				+ ((createUser == null) ? 0 : createUser.hashCode());
		result = prime * result + id;
		result = prime * result + ((money == null) ? 0 : money.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Outpay other = (Outpay) obj;
		if (classType == null) {
			if (other.classType != null)
				return false;
		} else if (!classType.equals(other.classType))
			return false;
		if (createTime == null) {
			if (other.createTime != null)
				return false;
		} else if (!createTime.equals(other.createTime))
			return false;
		if (createUser == null) {
			if (other.createUser != null)
				return false;
		} else if (!createUser.equals(other.createUser))
			return false;
		if (id != other.id)
			return false;
		if (money == null) {
			if (other.money != null)
				return false;
		} else if (!money.equals(other.money))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		return true;
	}

}
